#ifndef WITOS_USER_TEST_PROTOCOL_H
#define WITOS_USER_TEST_PROTOCOL_H
#include "witos/user_abi.h"

/* Test-only extension after the public startup prefix. */
#define WIT_TEST_NORMAL 0U
#define WIT_TEST_KERNEL_READ 1U
#define WIT_TEST_KERNEL_WRITE 2U
#define WIT_TEST_PRIVILEGED_CLI 3U
#define WIT_TEST_PRIVILEGED_PORT 4U
#define WIT_TEST_EXECUTE_DATA 5U
#define WIT_TEST_GUARD_LOW 6U
#define WIT_TEST_GUARD_HIGH 7U
#define WIT_TEST_WRITE_CODE 8U
#define WIT_TEST_WRITE_INFO 9U
#define WIT_TEST_PEER_READ 10U
#define WIT_TEST_SPIN 11U
#define WIT_TEST_NULL_READ 12U
#define WIT_TEST_INVALID_OPCODE 13U
#define WIT_TEST_BAD_RETURN 14U
#define WIT_TEST_PREEMPTION_STATE 15U
#define WIT_TEST_MEMORY_LIFECYCLE 16U
#define WIT_TEST_MEMORY_RESERVED 17U
#define WIT_TEST_MEMORY_DECOMMITTED 18U
#define WIT_TEST_MEMORY_RELEASED 19U
#define WIT_TEST_MEMORY_READONLY 20U
#define WIT_TEST_MEMORY_NOACCESS 21U
#define WIT_TEST_MEMORY_NX 22U
#define WIT_THREAD_TEST_NORMAL 0U
#define WIT_THREAD_TEST_CAPACITY 2U
#define WIT_THREAD_TEST_FAULT 3U
#define WIT_THREAD_TEST_GUARD_LOW 4U
#define WIT_THREAD_TEST_GUARD_HIGH 5U
#define WIT_THREAD_TEST_BAD_RETURN 6U
#define WIT_THREAD_TEST_PROCESS_EXIT 7U
/* The stack of the thread fixture's faulting thread (K8.3b): a reservation the fixture makes at this address of the data
 * arena, inside one 2 MiB region, so that the pages below and above it are known addresses with their page table. */
#define WIT_THREAD_TEST_STACK 0x0000010000210000ULL
#define WIT_THREAD_TEST_STACK_BYTES 16384U
#define WIT_WAIT_TEST_SIGNAL_STATE 0U
#define WIT_WAIT_TEST_CLOCK 1U
#define WIT_WAIT_TEST_AUTO 2U
#define WIT_WAIT_TEST_MANUAL 3U
#define WIT_WAIT_TEST_CLOSE 4U
#define WIT_WAIT_TEST_HANDOFF 5U
#define WIT_WAIT_TEST_DEADLINE 6U
#define WIT_WAIT_TEST_EXIT 7U
#define WIT_WAIT_TEST_BUDGET 8U
#define WIT_WAIT_TEST_RIGHTS 9U
#define WIT_WAIT_TEST_ACTIVE_TIMEOUT 10U
#define WIT_WAIT_TEST_JOIN_CHAIN 11U
#define WIT_EXCEPTION_TEST_NORMAL 0U
#define WIT_EXCEPTION_TEST_REJECT 1U
#define WIT_CHANNEL_TEST_BASIC 0U
#define WIT_CHANNEL_TEST_WAIT 1U
#define WIT_CHANNEL_TEST_TRANSFER 2U
#define WIT_CHANNEL_TEST_LIMITS 3U
#define WIT_CHANNEL_TEST_DROP 4U
#define WIT_MEMORY_OBJECT_TEST_BASIC 0U
#define WIT_MEMORY_OBJECT_TEST_CODE 1U
#define WIT_MEMORY_OBJECT_TEST_TRANSFER 2U
#define WIT_MEMORY_OBJECT_TEST_LIMITS 3U
#define WIT_MEMORY_OBJECT_TEST_EXIT 4U
#define WIT_DEVICE_TEST_TABLE 0U
#define WIT_DEVICE_TEST_AUTHORITY 1U
#define WIT_INTERRUPT_TEST_BIND 0U
#define WIT_INTERRUPT_TEST_DMA 1U
#define WIT_INTERRUPT_TEST_VIRTIO 2U
#define WIT_TEST_EXIT_CODE 42U
#define WIT_TEST_RO_OFFSET 24U
#define WIT_TEST_SELF_OFFSET 32U
#define WIT_TEST_FOREIGN_OFFSET 40U
#define WIT_TEST_MODE_OFFSET 48U
#define WIT_TEST_KERNEL_OFFSET 56U
#define WIT_TEST_INSTANCE_OFFSET 64U

typedef struct WitUserTestConfig {
    WitUserStartup Startup;
    WitU64 ReadOnlyHandle;
    WitU64 SelfHandle;
    WitU64 ForeignHandle;
    WitU64 Mode;
    WitU64 KernelProbe;
    WitU64 InstanceId;
    WitU64 TableHandle; /* the device table with ACQUIRE (K3.1) */
} WitUserTestConfig;

WIT_STATIC_ASSERT(sizeof(WitUserTestConfig) == 80, "User test config layout");
#define WIT_TEST_TABLE_OFFSET 72U
#endif
