#ifndef WITOS_NATIVE_DIAGNOSTICS_H
#define WITOS_NATIVE_DIAGNOSTICS_H
/* Private component exit reasons, not managed exception codes. */
#define WIT_NATIVE_PURECALL_EXIT 0xFFFF0002ULL
#define WIT_NATIVE_RANGECHECK_EXIT 0xFFFF0003ULL
#define WIT_NATIVE_GS_FAILURE_EXIT 0xFFFF0004ULL
#define WIT_NATIVE_GC_WRITE_WATCH_EXIT 0xFFFF0005ULL
#endif
