# Loaded only by CMAKE_PROJECT_CoreCLR_INCLUDE; upstream files stay unchanged.
# Defer until the upstream project has created the actual runtime target.
get_filename_component(WITOS_SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
function(witos_select_gc_environment)
    if(NOT TARGET Runtime.WorkstationGC OR NOT CLR_CMAKE_TARGET_WIN32 OR NOT CLR_CMAKE_TARGET_ARCH_AMD64)
        message(FATAL_ERROR "WitOS source overlay requires the pinned Windows AMD64 workstation runtime")
    endif()
    get_target_property(sources Runtime.WorkstationGC SOURCES)
    set(windows_gc "${CLR_DIR}/gc/windows/gcenv.windows.cpp")
    set(matches 0)
    foreach(source IN LISTS sources)
        if(source STREQUAL windows_gc)
            math(EXPR matches "${matches} + 1")
        endif()
    endforeach()
    if(NOT matches EQUAL 1)
        message(FATAL_ERROR "Expected exactly one upstream Windows GC environment source")
    endif()
    list(REMOVE_ITEM sources "${windows_gc}")
    list(APPEND sources "${WITOS_SOURCE_ROOT}/src/Runtime.NativeAot/gcenv.witos.cpp")
    set_property(TARGET Runtime.WorkstationGC PROPERTY SOURCES "${sources}")
    target_include_directories(Runtime.WorkstationGC PRIVATE
        "${WITOS_SOURCE_ROOT}/src/System.Native" "${WITOS_SOURCE_ROOT}/src/Kernel/include")
    file(WRITE "${CMAKE_BINARY_DIR}/witos-runtime-sources.txt" "${sources}\n")
    message(STATUS "WitOS: replaced GC memory environment; all missing methods remain undefined")
endfunction()
cmake_language(DEFER CALL witos_select_gc_environment)
