option casemap:none
include user_abi.inc
.code
PUBLIC wit_user_start
wit_user_start PROC
    mov rbx, WIT_USER_DATA
    mov rdi, [rbx]
    mov r12, [rbx+8]
    sub rsp, 40
    ; Exercise the real copied-request syscall before entering generated bytes.
    mov eax, WIT_CALL_CODE_MEMORY
    lea rcx, [rbx+128]
    mov edx, 64
    xor r8d, r8d
    int 80h
    test rax, rax
    jne failed
    test rdx, rdx
    jne failed
    call rdi
    cmp eax, 42
    jne failed
    test r12, r12
    jz passed
    cmp r12, 1
    je write_rx
    ; Revoke execute after a real call populated the active translation.
    mov eax, WIT_CALL_MEMORY_PROTECT
    mov rcx, rdi
    mov edx, 4096
    mov r8d, 3
    int 80h
    test rax, rax
    jne failed
    call rdi
    jmp failed
write_rx:
    mov byte ptr [rdi], 90h
    jmp failed
passed:
    mov ecx, 42
    mov eax, WIT_CALL_EXIT
    int 80h
failed:
    mov ecx, 0D001h
    mov eax, WIT_CALL_EXIT
    int 80h
    ud2
wit_user_start ENDP
END
