#ifndef WITOS_USER_TEST_PROTOCOL_H
#define WITOS_USER_TEST_PROTOCOL_H
#include "witos/user_abi.h"

/* Test-only extension after the public startup prefix. */
#define WIT_TEST_NORMAL 0U
#define WIT_TEST_KERNEL_READ 1U
#define WIT_TEST_KERNEL_WRITE 2U
#define WIT_TEST_PRIVILEGED_CLI 3U
#define WIT_TEST_PRIVILEGED_PORT 4U
#define WIT_TEST_EXECUTE_DATA 5U
#define WIT_TEST_GUARD_LOW 6U
#define WIT_TEST_GUARD_HIGH 7U
#define WIT_TEST_WRITE_CODE 8U
#define WIT_TEST_WRITE_INFO 9U
#define WIT_TEST_PEER_READ 10U
#define WIT_TEST_SPIN 11U
#define WIT_TEST_NULL_READ 12U
#define WIT_TEST_INVALID_OPCODE 13U
#define WIT_TEST_BAD_RETURN 14U
#define WIT_TEST_PREEMPTION_STATE 15U
#define WIT_TEST_MEMORY_LIFECYCLE 16U
#define WIT_TEST_MEMORY_RESERVED 17U
#define WIT_TEST_MEMORY_DECOMMITTED 18U
#define WIT_TEST_MEMORY_RELEASED 19U
#define WIT_TEST_MEMORY_READONLY 20U
#define WIT_TEST_MEMORY_NOACCESS 21U
#define WIT_TEST_MEMORY_NX 22U
#define WIT_THREAD_TEST_NORMAL 0U
#define WIT_THREAD_TEST_CYCLE 1U
#define WIT_THREAD_TEST_CAPACITY 2U
#define WIT_THREAD_TEST_FAULT 3U
#define WIT_THREAD_TEST_GUARD_LOW 4U
#define WIT_THREAD_TEST_GUARD_HIGH 5U
#define WIT_THREAD_TEST_BAD_RETURN 6U
#define WIT_THREAD_TEST_PROCESS_EXIT 7U
#define WIT_WAIT_TEST_SIGNAL_STATE 0U
#define WIT_WAIT_TEST_CLOCK 1U
#define WIT_WAIT_TEST_AUTO 2U
#define WIT_WAIT_TEST_MANUAL 3U
#define WIT_WAIT_TEST_CLOSE 4U
#define WIT_WAIT_TEST_HANDOFF 5U
#define WIT_WAIT_TEST_DEADLINE 6U
#define WIT_WAIT_TEST_EXIT 7U
#define WIT_WAIT_TEST_BUDGET 8U
#define WIT_WAIT_TEST_RIGHTS 9U
#define WIT_WAIT_TEST_ACTIVE_TIMEOUT 10U
#define WIT_WAIT_TEST_JOIN_CHAIN 11U
#define WIT_IMAGE_TEST_NORMAL 0U
#define WIT_IMAGE_TEST_WRITE_CODE 1U
#define WIT_IMAGE_TEST_WRITE_RO 2U
#define WIT_IMAGE_TEST_WRITE_HEADER 3U
#define WIT_IMAGE_TEST_EXECUTE_DATA 4U
#define WIT_IMAGE_TEST_END 5U
#define WIT_IMAGE_TEST_GAP 6U
#define WIT_BOOTSTRAP_TEST_NORMAL 0U
#define WIT_BOOTSTRAP_TEST_INIT_FAIL 1U
#define WIT_BOOTSTRAP_TEST_MAIN_FAIL 2U
#define WIT_BOOTSTRAP_TEST_BAD_INIT 3U
#define WIT_BOOTSTRAP_TEST_WRITABLE_TABLE 4U
#define WIT_BOOTSTRAP_TEST_BAD_MAIN 5U
#define WIT_BOOTSTRAP_TEST_TOO_MANY 6U
#define WIT_BOOTSTRAP_TEST_BAD_IMAGE 7U
#define WIT_BOOTSTRAP_TEST_WRITE_INFO 8U
#define WIT_BOOTSTRAP_TEST_INIT_FAULT 9U
#define WIT_BOOTSTRAP_TEST_EMPTY 10U
#define WIT_BOOTSTRAP_TEST_CONCURRENT 11U
#define WIT_GC_TEST_NORMAL 0U
#define WIT_GC_TEST_RESERVED 1U
#define WIT_GC_TEST_DECOMMITTED 2U
#define WIT_GC_TEST_NX 3U
#define WIT_GC_TEST_ROLLBACK 4U
#define WIT_TEST_EXIT_CODE 42U
#define WIT_TEST_RO_OFFSET 24U
#define WIT_TEST_SELF_OFFSET 32U
#define WIT_TEST_FOREIGN_OFFSET 40U
#define WIT_TEST_MODE_OFFSET 48U
#define WIT_TEST_KERNEL_OFFSET 56U
#define WIT_TEST_INSTANCE_OFFSET 64U

typedef struct WitUserTestConfig {
    WitUserStartup Startup;
    WitU64 ReadOnlyHandle;
    WitU64 SelfHandle;
    WitU64 ForeignHandle;
    WitU64 Mode;
    WitU64 KernelProbe;
    WitU64 InstanceId;
} WitUserTestConfig;
WIT_STATIC_ASSERT(sizeof(WitUserTestConfig) == 72, "User test config layout");
#endif
