option casemap:none
EXTERN GetModuleHandleW:PROC
EXTERN GetModuleFileNameW:PROC
EXTERN GetProcAddress:PROC
.code
PUBLIC wit_module_direct_handle
wit_module_direct_handle PROC
 jmp GetModuleHandleW
wit_module_direct_handle ENDP
PUBLIC wit_module_direct_filename
wit_module_direct_filename PROC
 jmp GetModuleFileNameW
wit_module_direct_filename ENDP
PUBLIC wit_module_direct_proc
wit_module_direct_proc PROC
 jmp GetProcAddress
wit_module_direct_proc ENDP
END
