option casemap:none
EXTERN wit_native_com_initialize:PROC
EXTERN wit_native_com_uninitialize:PROC
EXTERN wit_native_com_apartment:PROC
.code
PUBLIC CoInitializeEx
CoInitializeEx PROC
 jmp wit_native_com_initialize
CoInitializeEx ENDP
PUBLIC CoUninitialize
CoUninitialize PROC
 jmp wit_native_com_uninitialize
CoUninitialize ENDP
PUBLIC CoGetApartmentType
CoGetApartmentType PROC
 jmp wit_native_com_apartment
CoGetApartmentType ENDP
.const
ALIGN 8
PUBLIC __imp_CoInitializeEx
__imp_CoInitializeEx DQ CoInitializeEx
PUBLIC __imp_CoUninitialize
__imp_CoUninitialize DQ CoUninitialize
PUBLIC __imp_CoGetApartmentType
__imp_CoGetApartmentType DQ CoGetApartmentType
END
