option casemap:none
EXTERN wit_native_create_thread:PROC
EXTERN wit_native_set_thread_priority:PROC
EXTERN wit_native_reset_event:PROC
EXTERN wit_native_wait_single:PROC
EXTERN wit_native_wait_single_ex:PROC
.code
PUBLIC CreateThread
CreateThread PROC
 jmp wit_native_create_thread
CreateThread ENDP
PUBLIC SetThreadPriority
SetThreadPriority PROC
 jmp wit_native_set_thread_priority
SetThreadPriority ENDP
PUBLIC ResetEvent
ResetEvent PROC
 jmp wit_native_reset_event
ResetEvent ENDP
PUBLIC WaitForSingleObject
WaitForSingleObject PROC
 jmp wit_native_wait_single
WaitForSingleObject ENDP
PUBLIC WaitForSingleObjectEx
WaitForSingleObjectEx PROC
 jmp wit_native_wait_single_ex
WaitForSingleObjectEx ENDP
.const
ALIGN 8
PUBLIC __imp_CreateThread
__imp_CreateThread DQ CreateThread
PUBLIC __imp_SetThreadPriority
__imp_SetThreadPriority DQ SetThreadPriority
PUBLIC __imp_ResetEvent
__imp_ResetEvent DQ ResetEvent
PUBLIC __imp_WaitForSingleObject
__imp_WaitForSingleObject DQ WaitForSingleObject
PUBLIC __imp_WaitForSingleObjectEx
__imp_WaitForSingleObjectEx DQ WaitForSingleObjectEx
END
