option casemap:none
EXTERN wit_native_multibyte_to_wide:PROC
EXTERN wit_native_wide_to_multibyte:PROC
.code
PUBLIC MultiByteToWideChar
MultiByteToWideChar PROC
 jmp wit_native_multibyte_to_wide
MultiByteToWideChar ENDP
PUBLIC WideCharToMultiByte
WideCharToMultiByte PROC
 jmp wit_native_wide_to_multibyte
WideCharToMultiByte ENDP
.const
ALIGN 8
PUBLIC __imp_MultiByteToWideChar
PUBLIC __imp_WideCharToMultiByte
__imp_MultiByteToWideChar DQ MultiByteToWideChar
__imp_WideCharToMultiByte DQ WideCharToMultiByte
END
