option casemap:none
EXTERN wit_pal_environment_get:PROC
EXTERN wit_pal_environment_strings:PROC
EXTERN wit_pal_environment_free:PROC
EXTERN wit_pal_environment_set:PROC
.code
PUBLIC GetEnvironmentVariableW
PUBLIC wit_native_environment_get
GetEnvironmentVariableW PROC
wit_native_environment_get LABEL NEAR
    jmp wit_pal_environment_get
GetEnvironmentVariableW ENDP
PUBLIC GetEnvironmentStringsW
GetEnvironmentStringsW PROC
    jmp wit_pal_environment_strings
GetEnvironmentStringsW ENDP
PUBLIC FreeEnvironmentStringsW
FreeEnvironmentStringsW PROC
    jmp wit_pal_environment_free
FreeEnvironmentStringsW ENDP
PUBLIC SetEnvironmentVariableW
SetEnvironmentVariableW PROC
    jmp wit_pal_environment_set
SetEnvironmentVariableW ENDP
.const
ALIGN 8
PUBLIC __imp_GetEnvironmentVariableW
__imp_GetEnvironmentVariableW QWORD GetEnvironmentVariableW
PUBLIC __imp_GetEnvironmentStringsW
PUBLIC __imp_FreeEnvironmentStringsW
__imp_GetEnvironmentStringsW QWORD GetEnvironmentStringsW
__imp_FreeEnvironmentStringsW QWORD FreeEnvironmentStringsW
PUBLIC __imp_SetEnvironmentVariableW
__imp_SetEnvironmentVariableW QWORD SetEnvironmentVariableW
END
