option casemap:none
EXTERN wit_native_thread_id:PROC
EXTERN wit_native_current_process:PROC
EXTERN wit_native_current_thread:PROC
EXTERN wit_native_duplicate_handle:PROC
EXTERN wit_native_thread_priority:PROC
.code
PUBLIC GetCurrentThreadId
GetCurrentThreadId PROC
 jmp wit_native_thread_id
GetCurrentThreadId ENDP
PUBLIC GetCurrentProcess
GetCurrentProcess PROC
 jmp wit_native_current_process
GetCurrentProcess ENDP
PUBLIC GetCurrentThread
GetCurrentThread PROC
 jmp wit_native_current_thread
GetCurrentThread ENDP
PUBLIC DuplicateHandle
DuplicateHandle PROC
 jmp wit_native_duplicate_handle
DuplicateHandle ENDP
PUBLIC GetThreadPriority
GetThreadPriority PROC
 jmp wit_native_thread_priority
GetThreadPriority ENDP
.const
ALIGN 8
PUBLIC __imp_GetCurrentProcess
PUBLIC __imp_GetCurrentThread
PUBLIC __imp_DuplicateHandle
PUBLIC __imp_GetThreadPriority
PUBLIC __imp_GetCurrentThreadId
__imp_GetCurrentThreadId DQ GetCurrentThreadId
__imp_GetCurrentProcess DQ GetCurrentProcess
__imp_GetCurrentThread DQ GetCurrentThread
__imp_DuplicateHandle DQ DuplicateHandle
__imp_GetThreadPriority DQ GetThreadPriority
END
