option casemap:none
EXTERN wit_native_module_filename:PROC
EXTERN wit_native_module_handle:PROC
EXTERN wit_native_module_proc:PROC
.code
PUBLIC GetModuleFileNameW
GetModuleFileNameW PROC
 jmp wit_native_module_filename
GetModuleFileNameW ENDP
PUBLIC GetModuleHandleW
GetModuleHandleW PROC
 jmp wit_native_module_handle
GetModuleHandleW ENDP
PUBLIC GetProcAddress
GetProcAddress PROC
 jmp wit_native_module_proc
GetProcAddress ENDP
.const
ALIGN 8
PUBLIC __imp_GetModuleFileNameW
PUBLIC __imp_GetModuleHandleW
PUBLIC __imp_GetProcAddress
__imp_GetModuleFileNameW DQ GetModuleFileNameW
__imp_GetModuleHandleW DQ GetModuleHandleW
__imp_GetProcAddress DQ GetProcAddress
END
