option casemap:none
EXTERN wit_native_format_message:PROC
EXTERN wit_native_local_free:PROC
EXTERN wit_native_event_source:PROC
EXTERN wit_native_event_source_close:PROC
EXTERN wit_native_report_event:PROC
EXTERN wit_native_debugger_present:PROC
.code
PUBLIC FormatMessageW
FormatMessageW PROC
 jmp wit_native_format_message
FormatMessageW ENDP
PUBLIC LocalFree
LocalFree PROC
 jmp wit_native_local_free
LocalFree ENDP
PUBLIC RegisterEventSourceW
RegisterEventSourceW PROC
 jmp wit_native_event_source
RegisterEventSourceW ENDP
PUBLIC DeregisterEventSource
DeregisterEventSource PROC
 jmp wit_native_event_source_close
DeregisterEventSource ENDP
PUBLIC ReportEventW
ReportEventW PROC
 jmp wit_native_report_event
ReportEventW ENDP
PUBLIC IsDebuggerPresent
IsDebuggerPresent PROC
 jmp wit_native_debugger_present
IsDebuggerPresent ENDP
.const
ALIGN 8
PUBLIC __imp_FormatMessageW
__imp_FormatMessageW DQ FormatMessageW
PUBLIC __imp_LocalFree
__imp_LocalFree DQ LocalFree
PUBLIC __imp_RegisterEventSourceW
__imp_RegisterEventSourceW DQ RegisterEventSourceW
PUBLIC __imp_DeregisterEventSource
__imp_DeregisterEventSource DQ DeregisterEventSource
PUBLIC __imp_ReportEventW
__imp_ReportEventW DQ ReportEventW
PUBLIC __imp_IsDebuggerPresent
__imp_IsDebuggerPresent DQ IsDebuggerPresent
END
