option casemap:none
EXTERN wit_native_process_id:PROC
EXTERN wit_native_debug_output:PROC
EXTERN wit_native_create_directory:PROC
EXTERN wit_native_remove_directory:PROC
.code
PUBLIC GetCurrentProcessId
GetCurrentProcessId PROC
 jmp wit_native_process_id
GetCurrentProcessId ENDP
PUBLIC OutputDebugStringW
OutputDebugStringW PROC
 jmp wit_native_debug_output
OutputDebugStringW ENDP
PUBLIC CreateDirectoryW
CreateDirectoryW PROC
 jmp wit_native_create_directory
CreateDirectoryW ENDP
PUBLIC RemoveDirectoryW
RemoveDirectoryW PROC
 jmp wit_native_remove_directory
RemoveDirectoryW ENDP
.const
PUBLIC __imp_GetCurrentProcessId
__imp_GetCurrentProcessId DQ GetCurrentProcessId
PUBLIC __imp_OutputDebugStringW
__imp_OutputDebugStringW DQ OutputDebugStringW
PUBLIC __imp_CreateDirectoryW
__imp_CreateDirectoryW DQ CreateDirectoryW
PUBLIC __imp_RemoveDirectoryW
__imp_RemoveDirectoryW DQ RemoveDirectoryW
END
